name: servicio-menu-web-simulacion  # Nombre de la aplicación
services:
  - name: servicio-menu-web  # Nombre del servicio
    image: mftc2412/servicio-menu-web-simulacion:latest  # Imagen en Docker Hub
    envs:
      - key: PORT
        value: "80"
