name: Simulación CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Simular paso de construcción
        run: echo "Construyendo proyecto simulación servicio menú"

      - name: Simular paso de despliegue
        run: echo "Desplegando proyecto simulación servicio menú"
